# Generated by Django 5.2.6 on 2026-06-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('joining_date', models.DateField()),
                ('address', models.TextField()),
                ('teacher_image', models.ImageField(blank=True, upload_to='teachers/')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
    ]
