# Generated by Django 5.2.6 on 2026-06-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_parent_id_alter_student_id'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='Student.student'),
        ),
    ]
