# Generated by Django 6.0 on 2026-01-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='mother_occupation',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
