# Generated by Django 6.0 on 2026-01-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_parent_mother_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
