# Generated by Django 6.0 on 2026-01-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True, default='temp', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
